export const productData = [
  {
    id: '1',
    name: 'HP Smart Tank 589 AIO WiFi Color Printer',
    description:
      'Upto 6000 Black and 6000 Colour Pages of Ink in The Box. - Print, Scan & Copy for Office/Home',
    price: '₹13,999',
    mrp: '₹17,828',
    discount: '21% off',
    imageUrl:
      'https://m.media-amazon.com/images/I/31u6f4UOYhL._SX300_SY300_QL70_FMwebp_.jpg',
    category: 'printers',
  },
  {
    id: '2',
    name: 'HP Smart Tank 580 AIO WiFi Colour Printer',
    description:
      'with 1 Extra Black Ink Bottle (Upto 12000 Black & 6000 Colour Prints) + 1 Year Extended Warranty with PHA Coverage -Print, Scan & Copy',
    price: '₹14,619',
    mrp: '₹18,848',
    discount: '22% off',
    imageUrl:
      'https://m.media-amazon.com/images/I/31-GFfJdbcL._SX300_SY300_QL70_FMwebp_.jpg',
    category: 'printers',
  },
  {
    id: 'A110',
    name: 'Ducky One 2 Mini',
    brand: 'Ducky',
    price: 109.99,
    type: 'Wired',
    connection: 'USB',
    switchType: 'Mechanical',
    features: [
      'Compact design',
      'RGB lighting',
      'Detachable cable',
      'Durable design',
    ],
    imageUrl:
      'https://i.rtings.com/assets/products/cVIV7Lc4/ducky-one-2-mini-v1/design-medium.jpg?format=auto',
    category: 'keyboard',
  },
  {
    id: 'A112',
    name: 'HP K3500 Wireless Keyboard',
    brand: 'HP',
    price: 29.99,
    type: 'Wireless',
    connection: 'Bluetooth',
    switchType: 'Membrane',
    features: [
      'Compact design',
      'Long battery life',
      'Quiet typing',
      'Plug and play',
    ],
    imageUrl:
      'https://5.imimg.com/data5/SX/QA/MY-3324476/wireless-keyboard-250x250.jpg',
    category: 'keyboard',
  },

  {
    id: '3',
    name: 'HP Deskjet 2331 Colour Printer, Scanner and Copier',
    description:
      'for Home/Small Office, Compact Size, Reliable, Easy Set-Up Through HP Smart App On Your Pc Connected Through USB, Ideal for Home.',
    price: '₹3,799',
    mrp: '₹4,971',
    discount: '24% off',
    imageUrl:
      'https://5.imimg.com/data5/SELLER/Default/2022/3/KG/NI/SE/138669152/hp-deskjet-2331-colour-printer-scanner-and-copier-for.jpg',
    category: 'printers',
  },
  {
    id: '4',
    name: 'Canon PIXMA E477 ',
    description:
      'All in One (Print, Scan, Copy) WiFi Ink Efficient Colour Printer for Home/Student',
    price: '₹5,499',
    mrp: '₹6,355',
    discount: '13% off',
    imageUrl:
      'https://m.media-amazon.com/images/I/31qDdhE4QJL._SX300_SY300_QL70_FMwebp_.jpg',
    category: 'printers',
  },
  {
    id: '5',
    name: 'Canon Pixma MG2577s ',
    description: 'All-in-One Inkjet Colour Printer (Blue/White)',
    price: '₹3,249',
    mrp: '₹3,875',
    discount: '16% off',
    imageUrl:
      'https://m.media-amazon.com/images/I/31cSeRqDTwL._SX300_SY300_QL70_FMwebp_.jpg',
    category: 'printers',
  },
  {
    id: '6',
    name: 'HP Deskjet 2820 Printer, , Ideal for Home.',
    description:
      'Copy, Scan, WiFi with self Reset, Bluetooth, USB, Simple Setup Smart App',
    price: '₹5,299',
    mrp: '₹6,999',
    discount: '24% off',
    imageUrl: 'https://m.media-amazon.com/images/I/61oVMkLlMUL._SX679_.jpg',
    category: 'printers',
  },

  {
    id: 110,
    name: 'Anker Vertical Ergonomic Optical Mouse',
    brand: 'Anker',
    price: 24.99,
    dpi: 1600,
    wireless: true,
    connection: 'USB',
    features: [
      'Ergonomic design',
      '5 buttons',
      'Adjustable DPI',
      'Battery-powered',
    ],
    imageUrl:
      'https://m.media-amazon.com/images/I/61KDtOc39AL._AC_UF1000,1000_QL80_.jpg',
    category: 'mouse',
  },
  {
    id: 111,
    name: 'ASUS ROG Gladius II',
    brand: 'ASUS',
    price: 89.99,
    dpi: 12000,
    wireless: false,
    connection: 'USB',
    features: [
      'Customizable Aura Sync RGB lighting',
      'Swappable switches',
      'Ergonomic design',
      '6 programmable buttons',
    ],
    imageUrl: 'https://shedmart.in/wp-content/uploads/2021/01/811-1.jpg.webp',
    category: 'mouse',
  },
  {
    id: 112,
    name: 'Anker 2.4G Wireless Vertical Ergonomic Optical Mouse',
    brand: 'Anker',
    price: 19.99,
    dpi: 1600,
    wireless: true,
    connection: 'USB receiver',
    features: [
      'Ergonomic design',
      '5 buttons',
      'Adjustable DPI',
      'Battery-powered',
    ],
    imageUrl: 'https://m.media-amazon.com/images/I/61XzoCas8VL.jpg',
    category: 'mouse',
  },
  {
    id: '7',
    name: 'HP Ink Advantage Ultra 4929 Print, ',
    description:
      'Copy, Scan, Self Reset WiFi, Smart App Setup, Print per Page Cost Starting at 44paise/Page with 2 Additional Sets of Inks, Ideal for Home',
    price: '₹7,999',
    mrp: '₹10,404',
    discount: '23% off',
    imageUrl: 'https://m.media-amazon.com/images/I/61NmsHpYgrL._SX679_.jpg',
    category: 'printers',
  },
  {
    id: '8',
    name: 'HP Ink Advantage 4278 Printer',
    description:
      ' Automatic Document Feeder (ADF), Print, Copy, Scan,WiFi,Bluetooth, USB, Simple Setup Smart App, Ideal for Home.',
    price: '₹6,999',
    imageUrl:
      'https://m.media-amazon.com/images/I/31pfxEdQKuL._SX300_SY300_QL70_FMwebp_.jpg',
    category: 'printers',
  },
  {
    id: '9',
    name: 'Canon Pixma TS307',
    description:
      ' Single Function Wireless Inkjet Colour Printer (Black), Standard',
    price: '₹3,199',
    mrp: '₹3,595',
    discount: '11% off',
    imageUrl:
      'https://m.media-amazon.com/images/I/31VsJ2qMTfL._SX300_SY300_QL70_FMwebp_.jpg',
    category: 'printers',
  },

  {
    id: '10',
    name: 'HP Smart Tank 529 AIO Colour Printer ',
    description:
      '(Upto 6000 Black & 6000 Colour Pages Included in The Box)- Print, Scan & Copy for Office/Home',
    price: '₹10,999',
    mrp: '₹14,552',
    discount: '24% off',
    imageUrl:
      'https://m.media-amazon.com/images/I/31u6f4UOYhL._SX300_SY300_QL70_FMwebp_.jpg',
    category: 'printers',
  },
  {
    id: '11',
    name: 'Canon PIXMA E4570 ',
    description:
      'All in One (Print, Scan, Copy) WiFi Ink Efficient Colour Printer with FAX and Auto Duplex Printing for Home/Office',
    price: '₹7,980',
    mrp: '₹9,625',
    discount: '17% off',
    imageUrl:
      'https://m.media-amazon.com/images/I/41wksEYIENL._SX300_SY300_QL70_FMwebp_.jpg',
    category: 'printers',
  },
  {
    id: '12',
    name: 'Epson EcoTank L3210 ',
    description: 'A4 All-in-One Ink Tank Printer',
    price: '₹11,799',
    mrp: '₹14,999',
    discount: '21% off',
    imageUrl:
      'https://m.media-amazon.com/images/I/212bXfP108L._SY300_SX300_QL70_FMwebp_.jpg',
    category: 'printers',
  },
  {
    id: '13',
    name: 'Canon PIXMA MegaTank G3770 ',
    description:
      'Red All-in-one (Print, Scan, Copy) WiFi Inktank Colour Printer (Black 6000 Prints & Colour 7700 Prints) for Office,Scan The QR Code & Get a JBL Speaker Free on Registration',
    price: '₹13,499',
    mrp: '₹20,270',
    discount: '33% off',
    imageUrl:
      'https://m.media-amazon.com/images/I/410R6vCyOOL._SX300_SY300_QL70_FMwebp_.jpg',
    category: 'printers',
  },
  {
    id: '14',
    name: 'ZEITEL® Mini Bluetooth Thermal Printer,',
    description:
      ' Portable Label Printer Inkfree Printer for Android & iOS System, Black on White Thermal Printer with 10 Roll of Print Paper, Stickers, Blue',
    price: '₹1,999',
    mrp: '₹3,695',
    discount: '46% off',
    imageUrl:
      'https://m.media-amazon.com/images/I/41zaWMnKaYL._SY300_SX300_QL70_FMwebp_.jpg',
    category: 'printers',
  },
  {
    id: '15',
    name: 'SEZNIK Mini Printer,',
    description:
      ' Inkless, Bluetooth, Portable Pocket Printer, Compatible with Android, iOS Mobile. 1 Year Warranty (MiniX-Blue)',
    price: '₹2,249',
    mrp: '₹4,999',
    discount: '55% off',
    imageUrl:
      'https://m.media-amazon.com/images/I/51yh033slSL._SX300_SY300_QL70_FMwebp_.jpg',
    category: 'printers',
  },
  {
    id: '16',
    name: 'HP Laser 1008w Printer, ',
    description:
      'Wireless, Single Function, Print, Hi-Speed USB 2.0, Up to 21 ppm, 150-sheet Input Tray, 100-sheet Output Tray, 10,000-page Duty Cycle, 1-Year Warranty, Black and White, 714Z9A',
    price: '₹12,490',
    mrp: '₹15,840',
    discount: '21% off',
    imageUrl:
      'https://m.media-amazon.com/images/I/31cVA266+3L._SY300_SX300_.jpg',
    category: 'printers',
  },
  {
    id: '17',
    name: 'Epson L3251 Multi-function WiFi Color Ink Tank Printer',
    description: '4 Ink Bottles Included',
    price: '₹13,299',
    mrp: '₹17,999',
    discount: '26% off',
    imageUrl:
      'https://mediaserver.goepson.com/ImConvServlet/imconv/3679c7960a7a7a1feea5c47e1ee23470f69c52b0/1200Wx1200H?use=banner&hybrisId=B2C&assetDescr=L3250-%281%29',
    category: 'printers',
  },
  {
    id: '18',
    name: 'Epson L3200 Multi-function Color Ink Tank Printer',
    description: '4 Ink Bottles Included',
    price: '₹11,299',
    mrp: '₹14,999',
    discount: '24% off',
    imageUrl:
      'https://lalithatraders.com/wp-content/uploads/2023/04/Epson-EcoTank-L3200-Multi-function-Color-Inkjet-Printer-1.jpg',
    category: 'printers',
  },

  {
    id: '19',
    name: 'Canon MG2570S Multi-function Color Inkjet Printer',
    description: 'Ink Cartridge',
    price: '₹3,499',
    mrp: '₹3,875',
    discount: '9% off',
    imageUrl:
      'https://m.media-amazon.com/images/I/616QAphXlfL._AC_UF1000,1000_QL80_.jpg',
    category: 'printers',
  },
  {
    id: '20',
    name: 'Epson L3250 Multi-function WiFi Color Ink Tank Printer',
    description: '4 Ink Bottles Included',
    price: '₹14,199',
    mrp: '₹17,999',
    discount: '21% off',
    imageUrl:
      'https://rukminim2.flixcart.com/image/850/1000/xif0q/printer/e/k/r/-original-imagqsmzectcgpry.jpeg?q=20&crop=false',
    category: 'printers',
  },
  {
    id: '21',
    name: 'Canon PIXMA MG2470 All-in-One Inkjet Printer',
    description: 'Ink Cartridge',
    price: '₹3,249',
    mrp: '₹3,900',
    discount: '16% off',
    imageUrl:
      'https://printerpoint.co.in/wp-content/uploads/2020/04/canon-mg2470-original-imadqasfzxk7yzhd.jpeg',
    category: 'printers',
  },
  {
    id: '22',
    name: 'Canon PIXMA MegaTank/Ink',
    description:
      ' Efficient G3012 Multi-function WiFi Color Ink Tank Printer 6 Ink Bottles Included',
    price: '₹13,499',
    mrp: '₹18,775',
    discount: '28% off',
    imageUrl:
      'https://cdn.quicksell.co/-MNPJf9Lev0O7iqiclQN/products/-NxDRvsq3431V9gtXH9K.jpg',
    category: 'printers',
  },
  {
    id: '23',
    name: 'Epson L3210 Multi-function Color Ink Tank Printer',
    description: '4 Ink Bottles Included',
    price: '₹11,799',
    mrp: '₹14,999',
    discount: '21% off',
    imageUrl:
      'https://mediaserver.goepson.com/ImConvServlet/imconv/fd9185069111bb10312b33bec3c198b586527b19/515Wx515H?use=productpictures&hybrisId=B2C&assetDescr=L3256-%281%29',
    category: 'printers',
  },
  {
    id: '24',
    name: 'Epson EcoTank L3266 Multi-function WiFi Color Ink Tank Printer',
    description: '4 Ink Bottles Included',
    price: '₹14,999',
    mrp: '₹18,999',
    discount: '21% off',
    imageUrl:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ9bNLOWWi9dMwgiEOFng5MGtyyhrZ0FELnBQ&s',
    category: 'printers',
  },
  {
    id: '25',
    name: 'HP Smart Tank',
    description:
      ' All In One 589 Multi-function WiFi Color Ink Tank Printer for Print/Scan/Copy with Up to 6000 Black & 6000 color pages of ink in box',
    price: '₹13,999',
    mrp: '₹17,828',
    discount: '21% off',
    imageUrl: 'https://m.media-amazon.com/images/I/61uZGapgvFL.jpg',
    category: 'printers',
  },
  {
    id: '26',
    name: 'Epson L130 Single Function Inkjet Printer',
    description: '4 Ink Bottles Included',
    price: '₹8,799',
    mrp: '₹10,999',
    discount: '20% off',
    imageUrl: 'https://m.media-amazon.com/images/I/714bxKZ5NHL.jpg',
    category: 'printers',
  },
  {
    id: '27',
    name: 'HP Smart Tank ',
    description:
      'All In One 529 Multi-function Color Ink Tank Printer for Print/Scan/Copy with Up to 6000 Black & 6000 color pages of ink in box',
    price: '₹10,999',
    mrp: '₹13,825',
    discount: '20% off',
    imageUrl:
      'https://5.imimg.com/data5/SELLER/Default/2023/8/333536522/GB/IS/XY/98308581/hp-smart-tank-529-all-in-one-colour-printer-print-scan-copy-for-office-home-500x500.png',
    category: 'printers',
  },
  {
    id: '28',
    name: 'HP DeskJet Ink ',
    description:
      'Ink Cartridge Advantage 2778 Multi-function WiFi Color Inkjet Printer with Voice Activated Printing Google Assistant and Alexa with Copy, Scan, Bluetooth, USB, Simple setup with HP Smart App, Ideal for Home',
    price: '₹5,999',
    mrp: '₹8,450',
    discount: '29% off',
    imageUrl:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSUBNu5JYdUo0BR_jvq9fPzDzOCclkHxaK-rQ&s',
    category: 'printers',
  },
  // ----- KEYBOARD ------------
  {
    id: 'A11',
    name: 'Logitech MX Keys',
    brand: 'Logitech',
    price: 99.99,
    type: 'Wireless',
    connection: 'Bluetooth, USB',
    switchType: 'Scissor',
    features: [
      'Backlit keys',
      'Rechargeable battery',
      'Ergonomic design',
      'Multi-device support',
    ],
    imageUrl:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSPhTQ3Uq-_cK1O62OQ_IHm9WuKAAzvDdZPBA&s',
    category: 'keyboard',
  },
  {
    id: 'A12',
    name: 'Razer BlackWidow V3',
    brand: 'Razer',
    price: 139.99,
    type: 'Wired',
    connection: 'USB',
    switchType: 'Mechanical',
    features: [
      'RGB lighting',
      'Durable design',
      'Programmable keys',
      'Ergonomic wrist rest',
    ],
    imageUrl:
      'https://elitehubs.com/cdn/shop/products/razer-blackwidow-v3-mini-wireless-green-switch-image-01-600x600_result-2.jpg?v=1683974174',
    category: 'keyboard',
  },
  {
    id: 'A13',
    name: 'Apple Magic Keyboard',
    brand: 'Apple',
    price: 99.99,
    type: 'Wireless',
    connection: 'Bluetooth',
    switchType: 'Scissor',
    features: [
      'Slim design',
      'Rechargeable battery',
      'Multi-device support',
      'Compact size',
    ],
    imageUrl:
      'https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/MK293_AV3?wid=1144&hei=1144&fmt=jpeg&qlt=90&.v=1628007108000',
    category: 'keyboard',
  },
  {
    id: 'A14',
    name: 'Corsair K95 RGB Platinum XT',
    brand: 'Corsair',
    price: 199.99,
    type: 'Wired',
    connection: 'USB',
    switchType: 'Mechanical',
    features: [
      'RGB lighting',
      'Programmable macro keys',
      'Durable design',
      'Detachable wrist rest',
    ],
    imageUrl:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbrtpHYuNBEjY2YL2zLkzwQCvljiTtgVHpdA&s',
    category: 'keyboard',
  },
  {
    id: 'A15',
    name: 'SteelSeries Apex Pro',
    brand: 'SteelSeries',
    price: 199.99,
    type: 'Wired',
    connection: 'USB',
    switchType: 'Mechanical',
    features: [
      'Adjustable actuation switches',
      'OLED smart display',
      'RGB lighting',
      'Durable design',
    ],
    imageUrl:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQYYDgKpFPpXb7eQ9ez1lb0_LPyLXb7jM-85w&s',
    category: 'keyboard',
  },
  {
    id: 'A16',
    name: 'Microsoft Surface Keyboard',
    brand: 'Microsoft',
    price: 89.99,
    type: 'Wireless',
    connection: 'Bluetooth',
    switchType: 'Scissor',
    features: [
      'Ergonomic design',
      'Slim profile',
      'Quiet typing',
      'Long battery life',
    ],
    imageUrl:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTDMRpEGzEDyjSrNi_2oSikRVDHVl8Hu_SpEw&s',
    category: 'keyboard',
  },
  {
    id: 'A17',
    name: 'HyperX Alloy FPS Pro',
    brand: 'HyperX',
    price: 69.99,
    type: 'Wired',
    connection: 'USB',
    switchType: 'Mechanical',
    features: [
      'Compact design',
      'Red LED backlighting',
      'Durable design',
      'Detachable cable',
    ],
    imageUrl:
      'https://i.rtings.com/assets/products/4A0krySf/hyperx-alloy-fps-pro/design-medium.jpg?format=auto',
    category: 'keyboard',
  },
  {
    id: 'A18',
    name: 'Logitech G915 TKL',
    brand: 'Logitech',
    price: 229.99,
    type: 'Wireless',
    connection: 'Bluetooth, USB',
    switchType: 'Mechanical',
    features: [
      'RGB lighting',
      'Low profile switches',
      'Compact design',
      'LightSpeed wireless technology',
    ],
    imageUrl: 'https://m.media-amazon.com/images/I/61V2O4vbYhL.jpg',
    category: 'keyboard',
  },
  {
    id: 'A19',
    name: 'Razer Huntsman Elite',
    brand: 'Razer',
    price: 199.99,
    type: 'Wired',
    connection: 'USB',
    switchType: 'Opto-Mechanical',
    features: [
      'RGB lighting',
      'Magnetic wrist rest',
      'Durable design',
      'Programmable keys',
    ],
    imageUrl:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSKpIoQ5o3AbPA1eIfV_kGdjATSgD8w6CeNOg&s',
    category: 'keyboard',
  },

  // -------------- MOUSE --------------
  {
    id: 100,
    name: 'Logitech MX Master 3',
    brand: 'Logitech',
    price: 99.99,
    dpi: 4000,
    wireless: true,
    connection: 'Bluetooth, USB',
    features: [
      'Ergonomic design',
      'Customizable buttons',
      'Fast scrolling',
      'Rechargeable battery',
    ],
    imageUrl: 'https://m.media-amazon.com/images/I/613a-3jtieL.jpg',
    category: 'mouse',
  },
  {
    id: 101,
    name: 'Razer DeathAdder V2',
    brand: 'Razer',
    price: 69.99,
    dpi: 20000,
    wireless: false,
    connection: 'USB',
    features: [
      'Optical sensor',
      'Ergonomic design',
      'RGB lighting',
      'Programmable buttons',
    ],
    imageUrl:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQxnZt_IC0-Z3XBl2mJq3T982CWxXtL7AqWgg&s',
    category: 'mouse',
  },
  {
    id: 102,
    name: 'Apple Magic Mouse 2',
    brand: 'Apple',
    price: 79.99,
    dpi: 1300,
    wireless: true,
    connection: 'Bluetooth',
    features: [
      'Multi-Touch surface',
      'Rechargeable battery',
      'Sleek design',
      'Lightweight',
    ],
    imageUrl:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS4zV-h5OMCW8fAPmPMvJChReg930e5oEq-Sw&s',
    category: 'mouse',
  },
  {
    id: 103,
    name: 'Microsoft Surface Mouse',
    brand: 'Microsoft',
    price: 49.99,
    dpi: 1000,
    wireless: true,
    connection: 'Bluetooth',
    features: [
      'Ambidextrous design',
      'Metal scroll wheel',
      'Elegant design',
      'Long battery life',
    ],
    imageUrl: 'https://m.media-amazon.com/images/I/514apCBOV+L.jpg',
    category: 'mouse',
  },
  {
    id: 104,
    name: 'Corsair Dark Core RGB Pro SE',
    brand: 'Corsair',
    price: 89.99,
    dpi: 18000,
    wireless: true,
    connection: 'Bluetooth, USB',
    features: [
      'Customizable RGB lighting',
      'Qi wireless charging',
      'Ergonomic design',
      '9 programmable buttons',
    ],
    imageUrl: 'https://m.media-amazon.com/images/I/61RdgVQ43TL.jpg',
    category: 'mouse',
  },
  {
    id: 105,
    name: 'SteelSeries Rival 600',
    brand: 'SteelSeries',
    price: 79.99,
    dpi: 12000,
    wireless: false,
    connection: 'USB',
    features: [
      'Dual sensor system',
      'Adjustable weight system',
      'RGB lighting',
      'Split-trigger buttons',
    ],
    imageUrl:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTE3ixfVqPvh3_BhxI7N7pfabaCPe-faWtoiw&s',
    category: 'mouse',
  },
  {
    id: 106,
    name: 'Logitech G Pro Wireless',
    brand: 'Logitech',
    price: 129.99,
    dpi: 16000,
    wireless: true,
    connection: 'Bluetooth, USB',
    features: [
      'Lightweight design',
      'RGB lighting',
      'Hero sensor',
      'Long battery life',
    ],
    imageUrl:
      'https://computersolutionranchi.com/wp-content/uploads/2022/04/910-005274-image-1-600x600-1.jpg',
    category: 'mouse',
  },
  {
    id: 107,
    name: 'Razer Naga Trinity',
    brand: 'Razer',
    price: 99.99,
    dpi: 16000,
    wireless: false,
    connection: 'USB',
    features: [
      'Interchangeable side plates',
      'RGB lighting',
      'Ergonomic design',
      '12 programmable buttons',
    ],
    imageUrl: 'https://m.media-amazon.com/images/I/51gWmzc-WAL.jpg',
    category: 'mouse',
  },
  {
    id: 108,
    name: 'HP X3000 Wireless Mouse',
    brand: 'HP',
    price: 19.99,
    dpi: 1200,
    wireless: true,
    connection: 'Bluetooth',
    features: [
      'Ambidextrous design',
      'Compact size',
      'Scroll wheel',
      'Long battery life',
    ],
    imageUrl:
      'https://5.imimg.com/data5/HY/LA/JR/GLADMIN-33753135/hp-20x3000-800x800-500x500.jpg',
    category: 'mouse',
  },
  {
    id: 109,
    name: 'Logitech M185 Wireless Mouse',
    brand: 'Logitech',
    price: 14.99,
    dpi: 1000,
    wireless: true,
    connection: 'Bluetooth',
    features: [
      'Simple and reliable',
      'Compact size',
      'Long battery life',
      'Plug and play',
    ],
    imageUrl:
      'https://5.imimg.com/data5/SELLER/Default/2023/2/HF/IK/PJ/25753242/second-hand-laptop-500x500.jpg',
    category: 'mouse',
  },
];
